### ISSUE TITLE
Changes break org-noter-pdftools: org-noter--pdf-tools-edges-to-region has been renamed

### ISSUE THREAD

**Issue by rdiaz02** [org-noter/org-noter#6]
The current devel version breaks the use of org-noter from org-noter-pdftools. Note these problems do not occur with stable version 1.4.1. I am reporting several issues separately. 

Function `org-noter--pdf-tools-edges-to-region`: this function has been renamed to `org-noter-pdf--tools-edges-to-region`. This breaks its usage from org-noter-pdftools. Renaming back to `org-noter--pdf-tools-edges-to-region` restores functionality (at least in my limited testing).

**Comment by petermao** [comment]
I'll need to discuss this w/ @dmitrym0.

The rationale for the rename is that with @c1-g's refactoring of org-noter 1.4.1, we now have three modules supporting PDF, EPUB (nov) and DJVU.

Private functions use a `--` to separate the package from the rest of the function name, so it made more sense to normalize all the private functions in the modules as `org-noter-<module>--<remainder of function name>`.  Note that this project of renaming may not be complete, as we have not delved deeply into the `nov` and `djvu` modules.

In org-noter, this function is only used by the `org-noter-create-skeleton-pdf` function (and it should probably be renamed to `org-noter-pdf--create-skeleton`), [which is added in the pdf module to the list of hooks `org-noter-create-skeleton-functions`.](https://github.com/org-noter/org-noter/blob/e54e71b1029a532aee35ed7dfebecdc560b671d6/modules/org-noter-pdf.el#L378)

Perusing the code again, my feeling is that for org-noter, the proper name of the function should be either `org-noter-pdf--edges-to-regions` or `org-noter-pdf--convert-edges-to-regions` since the use of the [pdf-tools](https://github.com/vedang/pdf-tools/) package [is enforced](https://github.com/org-noter/org-noter/blob/e54e71b1029a532aee35ed7dfebecdc560b671d6/modules/org-noter-pdf.el#L215) long before [the function is called in org-noter](https://github.com/org-noter/org-noter/blob/e54e71b1029a532aee35ed7dfebecdc560b671d6/modules/org-noter-pdf.el#L266).

In the meantime, I will work on some changes to be nicer to downstream project (of which, I believe org-noter-pdftools is the only one.

**Comment by petermao** [comment]
@rdiaz02 let me know if the new commit fixed this problem for you.

**Comment by rdiaz02** [comment]
This seems to fix this issue, thanks! Should we close it?
